---
title: "Light partitioning "
author:
  - "Dr. Matthew Ross"
  - 'Dr. Jim Jawitz'
  - 'Dr. Matt Cohen'
date: '`r format(Sys.Date(), "%B %d, %Y")`'
site: bookdown::bookdown_site
documentclass: book
output:
  bookdown::gitbook: default
  #bookdown::pdf_book: default
editor_options: 
  chunk_output_type: console
---


# (PART) Motivation {-}

# Tiny intro

Water clarity and its components (chlorophyll a, total suspended sediment, and dissolved organic carbon) are among the most functionally important and socially-relevant aspects of water quality. Here we
propose a method for systematically evaluating the relative contribution
of each water clarity component to total clarity. We further borrow a 
visualization tool from soil analyses, the ternary diagram. We build 
ternary diagrams that partition light partitioning between DOC, algal cells, and non-algal particles. 


## Workflow


In its simplest form our workflow is:

1. Download all of [AquaSat](https://figshare.com/collections/AquaSat/4506140) and join disparate AquaSat pieces together

2. Investigate the relationship between chl-a, tis (inorganic sediment),
non-algal particles (dead particles), and algae biomass to build a
dataset of algal biomass, non-algal particle mass, and dissolved organic carbon mass. 

3. Investigate data quality of AquaSat and select a subset of data
where chl-a, doc, tss, and secchi were all measured simultaneously


4. Build a model that predicts light extinction (1.4/secchi)
using algal particles, non-algal particles, and doc.

5. Use this model to extract light extinction coefficients for 
each parameter, apply this model to visualizations in ternary space

6. Explore systematic controls on relative contribution to light
extinction over space and time across CONUS. 

